### ISSUE TITLE
L2 order book issue

### ISSUE THREAD

**Issue by Long199for** [Drakkar-Software/OctoBot-Trading#671]
Hi,
I am trying to use the L2 order book for strategies, while I got an issue on:
  File "octobot_trading/exchanges/connectors/cryptofeed_websocket_connector.py", line 642, in book
TypeError: Expected dict, got order_book.SortedDict

My exchange is gateio, so I changed a little like this:
class GateIOCryptofeedWebsocketConnector(exchanges.CryptofeedWebsocketConnector):
    REQUIRED_ACTIVATED_TENTACLES = []
    EXCHANGE_FEEDS = {
        Feeds.TRADES: cryptofeed_constants.TRADES,
        Feeds.KLINE: Feeds.UNSUPPORTED.value,
        Feeds.TICKER: cryptofeed_constants.TICKER,
        Feeds.CANDLE: Feeds.UNSUPPORTED.value,
        **Feeds.L2_BOOK: cryptofeed_constants.L2_BOOK,**
        Feeds.BOOK_DELTA: Feeds.UNSUPPORTED.value,
        Feeds.VOLUME: Feeds.UNSUPPORTED.value,
        Feeds.OPEN_INTEREST: Feeds.UNSUPPORTED.value,
    }

Then when I received the L2 in the first place from gateio:
2022-01-03 16:54:55 ERROR  WebSocketClient - gateio connection_handler.py:128      GATEIO.ws.2: error handling message {"time":1641228892,"channel":"spot.order_book_update","event":"update","result":{"t":1641228892277,"e":"depthUpdate","E":1641228892,"s":"ETH_USDT","U":4919664252,"u":4919664255,"b":[["3731.78","0"],["3742.62","0.0133"]],"a":[["3744.48","0.0083"],["3749.72","0"]]}}
2022-01-03 16:54:56 ERROR  WebSocketClient - gateio connection_handler.py:102      GATEIO.ws.2: encountered an exception, reconnecting in 1.0 seconds
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/cryptofeed/connection_handler.py", line 69, in _create_connection
    await self._handler(connection, self.handler)
  File "/opt/venv/lib/python3.8/site-packages/cryptofeed/connection_handler.py", line 119, in _handler
    await handler(message, connection, self.conn.last_message)
  File "/opt/venv/lib/python3.8/site-packages/cryptofeed/exchanges/gateio.py", line 254, in message_handler
    await self._process_l2_book(msg, timestamp)
  File "/opt/venv/lib/python3.8/site-packages/cryptofeed/exchanges/gateio.py", line 175, in _process_l2_book
    await self._snapshot(msg['result']['s'])
  File "/opt/venv/lib/python3.8/site-packages/cryptofeed/exchanges/gateio.py", line 135, in _snapshot
    await self.book_callback(L2_BOOK, self._l2_book[symbol], time.time(), raw=data, sequence_number=data['id'])
  File "/opt/venv/lib/python3.8/site-packages/cryptofeed/feed.py", line 190, in book_callback
    await self.callback(book_type, book, receipt_timestamp)
  File "/opt/venv/lib/python3.8/site-packages/cryptofeed/feed.py", line 201, in callback
    await cb(obj, receipt_timestamp)
  File "/opt/venv/lib/python3.8/site-packages/cryptofeed/callback.py", line 20, in __call__
    await self.callback(obj, receipt_timestamp)
  File "octobot_trading/exchanges/connectors/cryptofeed_websocket_connector.py", line 642, in book
TypeError: Expected dict, got order_book.SortedDict

I checked the code of the book function in the cryptofeed_websocket_connector.py:
book_instance.handle_book_adds(
            self._convert_book_prices_to_orders(
                book_prices=order_book.book.asks,
                book_side=trading_enums.TradeOrderSide.SELL.value) +
            self._convert_book_prices_to_orders(
                book_prices=order_book.book.bids,
                book_side=trading_enums.TradeOrderSide.BUY.value))
the book_prices is order_book.SortedDict, which should be fine.

I wonder why dict type is expected? Is it related to the .so which compiled by cpython?

**Comment by Herklos** [comment]
The OrderBook websocket feed is not yet supported.

**Comment by Long199for** [comment]
OK, Thanks any way
